Task2 grebenshchikova
Sdernal/net-kis pull request #10
Opened 2018-10-25 20:32 UTC by LizaGrebenshchikova

2018-10-25 21:08 UTC, Sdernal reviewed
В общем архитектура в корне нерабочая: нужно уметь добавлять любые провайдеры, а не те, которые прописаны в Фабрике. За этим и нужны дженерики и интерфейсы.

2018-10-25 21:08 UTC, Sdernal commented on csharpTasks/task2/Factory/Factory/Factory.cs
> +
А если я захочу совсем левый провайдер засунуть?

2018-10-25 21:08 UTC, Sdernal commented on csharpTasks/task2/Factory/Factory/Data.cs
> +    abstract class Vehicle: IMovable
Зачем абстрактный класс, если уже есть интерфейс?

2018-10-25 21:08 UTC, Sdernal commented on csharpTasks/task2/Factory/Factory/Factory.cs
> +            string type = typeof(T).Name;
Опять же, если я добавлю непредусмотренный провайдер, все сломается

2018-10-25 21:18 UTC, Sdernal commented
Да, и можно не заливать код в пулл-реквесте не относящийся к данному заданию. Делайте отдельные ветки для каждого задания.

2018-10-25 21:49 UTC, Sdernal requested changes
Забыл выставить Request changes

2018-12-08 13:29 UTC, Sdernal commented on csharpTasks/task2/Factory/Factory/Factory.cs
> +            return F.GetProvider<CarProvider>().CreateObject();
Тут нехорошо получится, если провайдера не окажется

2018-12-08 13:31 UTC, Sdernal commented on csharpTasks/task2/Factory/Factory/Providers.cs
> +        protected int NumDoors;
Почему бы не поиспользовать свойства? Мне кажется пользователю бы хотелось получить число дверей в своей машине только что с конвейера

2018-12-08 13:32 UTC, Sdernal commented on csharpTasks/task2/Factory/Factory/Program.cs
> +            //Car car2 = universalFactory.GetProvider<TruckProvider>().CreateObject();
Получение провайдера тоже должно работать

2018-12-08 13:34 UTC, Sdernal requested changes
В целом архитектура поправлена, но есть пара косяков, см. комменты

2018-12-09 16:04 UTC, LizaGrebenshchikova commented on csharpTasks/task2/Factory/Factory/Program.cs
> +            //Car car2 = universalFactory.GetProvider<TruckProvider>().CreateObject();
До этого метод работал некорректно, поправила.

2018-12-09 16:04 UTC, LizaGrebenshchikova commented on csharpTasks/task2/Factory/Factory/Providers.cs
> +        protected int NumDoors;
Поправила.

2018-12-09 16:05 UTC, LizaGrebenshchikova commented on csharpTasks/task2/Factory/Factory/Factory.cs
> +            return F.GetProvider<CarProvider>().CreateObject();
Поправила.

2018-12-09 16:10 UTC, Sdernal commented
За что вы так полюбили readonly-поля? Обычно в шарпах в основном свойства используют, ну да ладно. Принято.

2018-12-09 16:10 UTC, closed without merging