Task3 grebenshchikova
Sdernal/net-kis pull request #13
Opened 2018-11-13 18:04 UTC by LizaGrebenshchikova

2018-12-08 15:18 UTC, Sdernal commented on csharpTasks/task3/DelegatesApp/DelegatesApp/Market.cs
> +        private List<ISubscriber> Subscribers;
Не нашел, где они используются

2018-12-08 15:20 UTC, Sdernal commented on csharpTasks/task3/DelegatesApp/DelegatesApp/Market.cs
> +                count++;
Предполагалось, что покупается или продается count акций

2018-12-08 15:24 UTC, Sdernal requested changes
Почти ок, но в задании нужно два ISubscriber, изначально count в методах Sell и Buy - это сколько акций купит брокер, но в принципе и так сойдет

2018-12-09 13:04 UTC, Sdernal commented on csharpTasks/task3/DelegatesApp/DelegatesApp/Market.cs
> +                count++;
Мой косяк, так сойдет

2018-12-09 13:06 UTC, Sdernal commented
В общем, похоже я накосячил в формулировке Sell и Buy. Добавь еще одного ISubscriber с измененной логикой "торговли" и зачтем

2018-12-09 16:24 UTC, LizaGrebenshchikova commented on csharpTasks/task3/DelegatesApp/DelegatesApp/Market.cs
> +        private List<ISubscriber> Subscribers;
Поправила.

2018-12-09 16:32 UTC, Sdernal commented on csharpTasks/task3/DelegatesApp/DelegatesApp/Broker.cs
> +    public class Broker2 : ISubscriber
Ну за такое наименование в проде принято по рукам бить,  Назови хоть DifferenceOrientedBroker и maxDiff можно в конструктор перенести

2018-12-09 16:59 UTC, LizaGrebenshchikova commented on csharpTasks/task3/DelegatesApp/DelegatesApp/Broker.cs
> +    public class Broker2 : ISubscriber
Поправила.

2018-12-09 17:00 UTC, Sdernal commented
Ок. Принято

2018-12-09 17:00 UTC, closed without merging