Task3 vinokurov
Sdernal/net-kis pull request #14
Opened 2018-11-13 18:10 UTC by pyspice

2018-12-08 15:27 UTC, Sdernal commented on csharpTasks/task3/DelegatesApp/DelegatesApp/Persons.cs
> +using System.Linq;
Суть этой части задания, чтобы самому написать пару методов из LINQ, а не использовать его

2018-12-08 15:32 UTC, Sdernal requested changes

2018-12-08 15:32 UTC, Sdernal commented on csharpTasks/task3/DelegatesApp/DelegatesApp/Broker.cs
> +                market.Buy(args.ShareName, ref stocks, ref brokerMoney);
Все-таки странно покупать акции, столько же, сколько есть и сейчас. А по логике этого метода у него так ничего и не появится. В задании нужно реализовать двух ISubscriber, пусть у второго будет другая логика: например покупать акции, если цена на них больше некоторой суммы, и продавать, при втором пороге.

2018-12-09 12:48 UTC, pyspice commented on csharpTasks/task3/DelegatesApp/DelegatesApp/Persons.cs
> +using System.Linq;
Полезное задание.
Поправил.

2018-12-09 12:57 UTC, pyspice commented on csharpTasks/task3/DelegatesApp/DelegatesApp/Broker.cs
> +                market.Buy(args.ShareName, ref stocks, ref brokerMoney);
<img width="629" alt="untitled" src="https://user-images.githubusercontent.com/26696088/49697591-982f4380-fbca-11e8-8185-278833e120ca.png">
Исходя из начальной доки, при покупке биржа прибавляет к stocks некоторое количество акций. Если задание меняется, просьба уведомлять об этом.

2018-12-09 13:01 UTC, Sdernal commented on csharpTasks/task3/DelegatesApp/DelegatesApp/Broker.cs
> +                market.Buy(args.ShareName, ref stocks, ref brokerMoney);
А, тогда мой косяк. Я когда пытался сформулировать нормально эту часть задания, раз десять его менял. Доделывай второго брокера и зачтем

2018-12-09 13:10 UTC, pyspice commented on csharpTasks/task3/DelegatesApp/DelegatesApp/Broker.cs
> +                market.Buy(args.ShareName, ref stocks, ref brokerMoney);
Блин, просто в таком случае второй брокер не имеет смысла, т.к. маркет либо полностью продает, либо покупает на все деньги брокера один вид акций. Фактически, для маркета любой ISubscriber - один и тот же с точностью до состояния. Если хочется второго брокера, просьба обновить задание.

2018-12-09 13:14 UTC, Sdernal commented on csharpTasks/task3/DelegatesApp/DelegatesApp/Broker.cs
> +                market.Buy(args.ShareName, ref stocks, ref brokerMoney);
Тут ты рандомно говорил покупать или продавать все, просто скопипасть и сделай чтобы он продавал/покупал (также все), если цена на акцию больше/меньше некоторого порога(порогов).

2018-12-09 14:55 UTC, pyspice commented on csharpTasks/task3/DelegatesApp/DelegatesApp/Broker.cs
> +                market.Buy(args.ShareName, ref stocks, ref brokerMoney);
Ну, ок. Поправил.

2018-12-09 14:58 UTC, Sdernal commented
Сильно. Ок, принято

2018-12-09 14:58 UTC, closed without merging