Task2 added
Sdernal/net-kis pull request #15
Opened 2018-11-25 11:17 UTC by pyspice

2018-12-08 15:38 UTC, Sdernal requested changes
Ну... сойдет, но в задании еще указывались тесты. Добавь парочку на xUnit. В .Net 1.5 есть примеры

2018-12-08 15:38 UTC, Sdernal commented on csharpTasks/task4/LinqTask/LinqTask/ReviewContext.cs
> +            Func<int, IEnumerable<string>> getMovies = userId => reviews_.Where(review => review.UserId == userId)
а Join не проще?

2018-12-09 13:23 UTC, pyspice commented on csharpTasks/task4/LinqTask/LinqTask/ReviewContext.cs
> +            Func<int, IEnumerable<string>> getMovies = userId => reviews_.Where(review => review.UserId == userId)
Я не запускаю это на больших данных на мейнфрейме с оптимизированной СУБД, так что различий в производительности быть не должно. Если вопрос про размер/сложность кода, то одинаково.

2018-12-09 15:57 UTC, Sdernal commented on csharpTasks/task4/LinqTask/XUnitTestProject1/UnitTest1.cs
> +        public void Test1()
Это не совсем те тесты, которые нужно: на каждый кейс делается один [Fact], в котором собственно есть три стадии: Arrange - где мы подготавливаем данные, Act - где мы собственно делаем некоторые действия с помощью тестируемого модуля и Assert - проверяем, что выполнились некоторые условия.
В xUnit есть уже куча методов у объекта Assert, который занимается проверкой условий, например Assert.Equal(expected, value). т.е. класс с тестами должен состоять из набора Fact-ов и Theory (Параметризуемый тест). В каждом факте собственно должно быть что-то такое:

""" 
[Fact]
publc void GetUserReviewsTest() {
// Arrange
List<Review> reviews = GenerateData(); // Некий приватный метод в этом классе, который генерирует коллекцию
var reviewContext = new ReviewContext(reviews);
// Act
 var result = reviewContext.GetUserReviews(1).Count();
// Assert
Assert.Equal(2, result);
}
}
"""

Можешь здесь прочитать подробнее про юнит-тесты: https://metanit.com/sharp/aspnet5/22.1.php
Там и как запускать и как писать описано.

2018-12-09 16:50 UTC, pyspice commented on csharpTasks/task4/LinqTask/XUnitTestProject1/UnitTest1.cs
> +        public void Test1()
Ок, учту на будущее.

2018-12-09 16:52 UTC, Sdernal commented on csharpTasks/task4/LinqTask/XUnitTestProject1/UnitTest1.cs
> +        public void Test1()
Но здесь все-таки нужно переписать хотя бы пару-тройку кейсов на фреймворк xUnit

2018-12-09 19:02 UTC, pyspice commented on csharpTasks/task4/LinqTask/XUnitTestProject1/UnitTest1.cs
> +        public void Test1()
Сделал

2018-12-09 19:02 UTC, Sdernal commented
Ок. Принято

2018-12-09 19:02 UTC, closed without merging