Винокуров Сергей, task1
Sdernal/net-kis pull request #2
Opened 2018-09-25 16:12 UTC by pyspice

Добавлены property x, y

2018-10-02 15:32 UTC, Sdernal requested changes
Комментарии к коду

2018-10-02 15:32 UTC, Sdernal commented on csharpTasks/task1/MyVector/MyVector/Vector.cs
> +        public double x { get; private set; }
Студия должна была подсказать, что свойства называют с большой буквы

2018-10-02 15:32 UTC, Sdernal commented on csharpTasks/task1/MyVector/MyVector/Program.cs
> +
А где проверки на нулевой вектор?

2018-10-02 15:32 UTC, Sdernal commented on csharpTasks/task1/MyVector/MyVector/Vector.cs
> +            return this;
Мы же на паре обсуждали, что должен возвращаться новый объект

2018-10-02 15:32 UTC, Sdernal commented on csharpTasks/task1/MyVector/MyVector/Vector.cs
>          public static Vector operator+ (Vector v, Vector u)
Хотя бы у одного оператора сделать доки нужно

2018-10-02 15:32 UTC, Sdernal commented on csharpTasks/task1/MyVector/MyVector/VectorExtensions.cs
> +            return new Vector();
Что за вектор вернется?

2018-10-02 15:32 UTC, Sdernal commented on csharpTasks/task1/MyVector/MyVector/VectorExtensions.cs
> +            return Math.Atan2(v.CrossProduct(u), v.DotProduct(u));
Что вернет, если один из них 0?

2018-10-02 15:32 UTC, Sdernal commented on csharpTasks/task1/MyVector/MyVector/Vector.cs
> +            this.x += v.x;
По поводу использования this, кому-то это не нравится, но я не вижу в этом ничего плохого. В общем, можно не менять, но тогда нужно соблюдать один стиль. Вроде у тебя с этим ок.

2018-10-02 15:32 UTC, Sdernal commented on csharpTasks/task1/MyVector/MyVector/VectorExtensions.cs
> +            return new Vector(-v.y, v.x) / v.Length();
Проверка на 0

2018-10-02 15:32 UTC, Sdernal commented on csharpTasks/task1/MyVector/MyVector/Vector.cs
> +            return new Vector(v.x / k, v.y / k);
Передам k = 0 и все сломается, лучше самому кидать исключение, что не тот аргумент

2018-10-13 21:14 UTC, pyspice commented on csharpTasks/task1/MyVector/MyVector/Vector.cs
> +        public double x { get; private set; }
Не подсказала(

2018-10-13 21:15 UTC, pyspice commented on csharpTasks/task1/MyVector/MyVector/Program.cs
> +
Ну камон, мы же даже еще исключения кидать не умеем)

2018-10-13 21:21 UTC, pyspice commented on csharpTasks/task1/MyVector/MyVector/Vector.cs
>          public static Vector operator+ (Vector v, Vector u)
Ну блин, док оператора же ничем не отличается от дока функции
Но я сделал на всякий случай, чтобы проверить

2018-10-13 21:23 UTC, pyspice commented on csharpTasks/task1/MyVector/MyVector/VectorExtensions.cs
> +            return new Vector();
Из нулей, очевидно

2018-10-13 21:27 UTC, pyspice commented on csharpTasks/task1/MyVector/MyVector/VectorExtensions.cs
> +            return Math.Atan2(v.CrossProduct(u), v.DotProduct(u));
0 в обоих случаях, но это снова к вопросу о кастомных исключениях

2018-10-13 21:28 UTC, pyspice commented on csharpTasks/task1/MyVector/MyVector/VectorExtensions.cs
> +            return new Vector(-v.y, v.x) / v.Length();
снова, по-хорошему нужно прилагать к вектору исключения для вектора

2018-10-13 21:32 UTC, pyspice commented on csharpTasks/task1/MyVector/MyVector/Vector.cs
> +            return new Vector(v.x / k, v.y / k);
ладно-ладно, кину

2018-10-25 21:37 UTC, Sdernal commented on csharpTasks/task1/MyVector/MyVector/Program.cs
> +
Можно возвращать фиксированное значение

2018-10-25 21:42 UTC, Sdernal commented on csharpTasks/task1/MyVector/MyVector/VectorExtensions.cs
> +            return new Vector();
Пользователю это не очевидно. Почему бы не вернуть с бесконечными координатми. Нужно явно указывать, что мы считаем нулевым или невалидным вектором.

2018-10-25 21:43 UTC, Sdernal commented on csharpTasks/task1/MyVector/MyVector/VectorExtensions.cs
> +            return Math.Atan2(v.CrossProduct(u), v.DotProduct(u));
Нужно явно обрабатывать краевые случаи, а не полагаться на реализацию Math.Atan2

2018-10-25 21:45 UTC, Sdernal commented on csharpTasks/task1/MyVector/MyVector/VectorExtensions.cs
> +            return new Vector(-v.y, v.x) / v.Length();
Можно, но раз мы на тот момент не проходили исключения, то лучшим вариантом будет возвращение какого-то фиксированного значения. При этом не лишним будет указать это в документации

2018-10-25 21:46 UTC, Sdernal commented
В общем, мне пока еще не нравится.

2018-12-09 11:58 UTC, pyspice commented on csharpTasks/task1/MyVector/MyVector/Program.cs
> +
Не очень ясно, каким образом выделенный сниппет связан с комментарием

2018-12-09 12:19 UTC, Sdernal commented on csharpTasks/task1/MyVector/MyVector/Program.cs
> +
Вижу вектора, не вижу нулевого

2018-12-09 12:28 UTC, pyspice commented on csharpTasks/task1/MyVector/MyVector/Vector.cs
> +            return this;
Комментарий устарел

2018-12-09 12:29 UTC, pyspice commented on csharpTasks/task1/MyVector/MyVector/Program.cs
> +
Добавлены проверки с нулевым вектором

2018-12-09 12:30 UTC, pyspice commented on csharpTasks/task1/MyVector/MyVector/VectorExtensions.cs
> +            return new Vector();
Поправил доку

2018-12-09 12:30 UTC, pyspice commented on csharpTasks/task1/MyVector/MyVector/VectorExtensions.cs
> +            return Math.Atan2(v.CrossProduct(u), v.DotProduct(u));
Поправил

2018-12-09 12:30 UTC, pyspice commented on csharpTasks/task1/MyVector/MyVector/Vector.cs
> +            this.x += v.x;
Ок

2018-12-09 12:31 UTC, pyspice commented on csharpTasks/task1/MyVector/MyVector/VectorExtensions.cs
> +            return new Vector(-v.y, v.x) / v.Length();
Поправил

2018-12-09 12:33 UTC, Sdernal commented
В общем принято. На будущее: свойства принято называть с большой буквы

2018-12-09 12:33 UTC, closed without merging