Task1
Sdernal/net-kis pull request #21
Opened 2019-03-22 19:38 UTC by NikitaSikalov

Тесты прописал. Документацию не стал везде прописывать, попробовал пару раз и понял.

2019-04-05 19:12 UTC, Sdernal requested changes
Подумай над вопросами, ответь на них или поправь

2019-04-05 19:12 UTC, Sdernal commented on csharpTasks/task1/MyVector/MyVector/Vector.cs
> +        public double X;
обычно структуры делают иммутабельными, почему такое определение может этому помешать?

2019-04-05 19:12 UTC, Sdernal commented on csharpTasks/task1/MyVector/MyVector/Vector.cs
>          public Vector Add(Vector v)
Тоже приводит к мутабельности типа

2019-04-05 19:12 UTC, Sdernal commented on csharpTasks/task1/MyVector/MyVector/Vector.cs
> +            Vector new_vector = v;
Логика отличается от того что идет далее, с чем это связано

2019-04-05 19:12 UTC, Sdernal commented on csharpTasks/task1/MyVector/MyVector/Vector.cs
> +            Vector new_vector = v;
и как же все-таки лучше сделать

2019-04-05 19:12 UTC, Sdernal commented on csharpTasks/task1/MyVector/MyVector/Vector.cs
> +        public static Vector operator-(Vector v, Vector u)
Хотя бы пару методов и операторов можно было бы и прокомментировать

2019-04-05 19:12 UTC, Sdernal commented on csharpTasks/task1/MyVector/MyVector/VectorExtensions.cs
> +            return v.Scale(1 / v.Length());
не проще применить оператор деления?

2019-04-05 19:12 UTC, Sdernal commented on csharpTasks/task1/MyVector/MyVector/VectorExtensions.cs
> +            return Math.Acos(v.DotProduct(u) / v.Length() / u.Length());
Я бы добавил сюда проверку, чтобы скрыть от пользователя реализацию, что упадет в методе Length

2019-05-17 18:59 UTC, NikitaSikalov commented on csharpTasks/task1/MyVector/MyVector/Vector.cs
> +        public double X;
потому что поле public
```suggestion
        private double _x;
```

2019-05-17 19:03 UTC, NikitaSikalov commented on csharpTasks/task1/MyVector/MyVector/Vector.cs
> +            Vector new_vector = v;
Потому что + это оператор, который возвращает некоторое значение, но при этом он не изменяет сами операнды (в отличие от += или -= и т. п.)

2019-05-17 19:32 UTC, NikitaSikalov commented
Исправил описанные выше ошибки

2019-05-17 19:45 UTC, Sdernal commented on csharpTasks/task1/MyVector/MyVector/Vector.cs
> +            Vector new_vector = v;
Не обязательно, обсудим на зачете

2019-05-17 19:45 UTC, Sdernal commented
Принято

2019-05-17 19:45 UTC, closed without merging