task3 delegates
Sdernal/net-kis pull request #25
Opened 2019-04-01 15:56 UTC by sunruslan

2019-04-05 19:46 UTC, Sdernal requested changes
Там подозрительная опечатка, хоть запускалось?

2019-04-05 19:46 UTC, Sdernal commented on csharpTasks/task3/DelegatesApp/DelegatesApp/AppleBroker.cs
> +            var differenсу = args.NewPrice = args.OldPrice;
Опечатка?

2019-04-05 21:23 UTC, sunruslan commented on csharpTasks/task3/DelegatesApp/DelegatesApp/AppleBroker.cs
> +            var differenсу = args.NewPrice = args.OldPrice;
да, поправил

2019-04-06 06:14 UTC, Sdernal commented
Принято

2019-04-06 06:14 UTC, closed without merging