Added first task
Sdernal/net-kis pull request #27
Opened 2019-04-03 11:10 UTC by maximborodin

2019-04-03 11:11 UTC, maximborodin commented
There is my vision of the first task

2019-04-05 19:33 UTC, Sdernal requested changes
Есть что поправить

2019-04-05 19:33 UTC, Sdernal commented on csharpTasks/task1/MyVector/MyVector/Vector.cs
> +        public double x, y;
Мутабельность структур

2019-04-05 19:33 UTC, Sdernal commented on csharpTasks/task1/MyVector/MyVector/Vector.cs
>          public Vector Add(Vector v)
Мутабельность

2019-04-05 19:33 UTC, Sdernal commented on csharpTasks/task1/MyVector/MyVector/Vector.cs
> +        public static Vector operator- (Vector v, Vector u)
Пару операторов можно было бы и прокомментировать

2019-04-05 19:33 UTC, Sdernal commented on csharpTasks/task1/MyVector/MyVector/VectorExtensions.cs
> +            return Math.Acos(v.DotProduct(u) / (v.Length() * u.Length()));
деления на 0 тут не отхватим случаем?

2019-04-05 19:33 UTC, Sdernal commented on csharpTasks/task1/MyVector/MyVector/VectorExtensions.cs
> +            if (Math.Abs(product) == v.Length() * u.Length()) {
сравнивать даблы на равенство - плохая идея

2019-04-05 19:33 UTC, Sdernal commented on csharpTasks/task1/MyVector/MyVector/Program.cs
> +            // Console.WriteLine("Hello world!");
Проверка краевых случаев

2019-05-10 11:37 UTC, maximborodin commented on csharpTasks/task1/MyVector/MyVector/Vector.cs
> +        public double x, y;
Fixed

2019-05-10 11:38 UTC, maximborodin commented on csharpTasks/task1/MyVector/MyVector/Vector.cs
>          public Vector Add(Vector v)
Fixed

2019-05-10 11:38 UTC, maximborodin commented on csharpTasks/task1/MyVector/MyVector/Vector.cs
> +        public static Vector operator- (Vector v, Vector u)
Fixed

2019-05-10 11:38 UTC, maximborodin commented on csharpTasks/task1/MyVector/MyVector/VectorExtensions.cs
> +            return Math.Acos(v.DotProduct(u) / (v.Length() * u.Length()));
Fixed

2019-05-10 11:38 UTC, maximborodin commented on csharpTasks/task1/MyVector/MyVector/VectorExtensions.cs
> +            if (Math.Abs(product) == v.Length() * u.Length()) {
Ok

2019-05-10 11:38 UTC, maximborodin commented on csharpTasks/task1/MyVector/MyVector/Program.cs
> +            // Console.WriteLine("Hello world!");
Added something

2019-05-17 13:01 UTC, Sdernal requested changes

2019-05-17 13:01 UTC, Sdernal commented on csharpTasks/task1/MyVector/MyVector/Vector.cs
> +            if (Math.Abs(k) < 0.00001) {
Хардкодить константу такое себе

2019-05-17 13:01 UTC, Sdernal commented on csharpTasks/task1/MyVector/MyVector/VectorExtensions.cs
> +            if (Math.Abs(v.Length()) < 0.00001) {
Хардкод

2019-05-17 13:01 UTC, Sdernal commented on csharpTasks/task1/MyVector/MyVector/VectorExtensions.cs
> +            if (Math.Abs(v.Length() * u.Length()) < 0.0000000001)
Хардкод

2019-05-17 13:01 UTC, Sdernal commented on csharpTasks/task1/MyVector/MyVector/VectorExtensions.cs
>                  return VectorRelation.Orthogonal;
хардкод

2019-05-17 16:21 UTC, maximborodin commented on csharpTasks/task1/MyVector/MyVector/Vector.cs
> +            if (Math.Abs(k) < 0.00001) {
FIxed

2019-05-17 19:42 UTC, Sdernal commented
Принято

2019-05-17 19:42 UTC, closed without merging