Task1
Sdernal/net-kis pull request #3
Opened 2018-10-01 19:59 UTC by LizaGrebenshchikova

2018-10-01 20:07 UTC, Sdernal commented
Нет проверок на нулевой вектор

2018-10-01 20:21 UTC, Sdernal reviewed
Я не видел, чтобы был задокументирован хоть один параметр или возвращаемое значение

2018-10-01 20:21 UTC, Sdernal commented on csharpTasks/task1/MyVector/MyVector/Vector.cs
> +        public double X_ { get; private set; }
Это не приватное поле, чтоб его с подчеркиванием писать, пользователь не сильно обрадуется, когда ему придется писать new Vector(1,1).X_, а не просто X

2018-10-01 20:21 UTC, Sdernal commented on csharpTasks/task1/MyVector/MyVector/Vector.cs
> +        /// <returns></returns>
Параметры и возвращаемое значение тоже нужно документировать

2018-10-01 20:21 UTC, Sdernal commented on csharpTasks/task1/MyVector/MyVector/Vector.cs
> +            Vector result = new Vector(X_ + v.X_,Y_ + v.Y_);
по мне так по чему бы сразу не вернуть new Vector, использование локальной переменной здесь не обоснованно

2018-10-01 20:21 UTC, Sdernal commented on csharpTasks/task1/MyVector/MyVector/Vector.cs
> +            String result = '(' + this.X_.ToString() + ", " + this.Y_.ToString() + ')';
Есть же красивые inline-строки: return $"({X}, {Y})"

2018-10-01 20:21 UTC, Sdernal commented on csharpTasks/task1/MyVector/MyVector/Vector.cs
> +            double result_X = v.X_ + u.X_;
Также необоснованное использование локальных переменных

2018-10-01 20:21 UTC, Sdernal commented on csharpTasks/task1/MyVector/MyVector/Vector.cs
> +                throw new DivideByZeroException();
нормас

2018-10-01 20:21 UTC, Sdernal commented on csharpTasks/task1/MyVector/MyVector/VectorExtensions.cs
> +                result = new Vector(v.X_ / v.Length(), v.Y_ / v.Length());
А не проще длину с нулем сравнить?

2018-10-01 20:21 UTC, Sdernal commented on csharpTasks/task1/MyVector/MyVector/VectorExtensions.cs
> +            if (Math.Abs(v.Length()) < eps  || Math.Abs(u.Length()) < eps )
Тут можно по-разному считать: нулевой вектор может быть сонаправлен любому, но вот кидать деление  на 0 как-то странно

2018-10-25 20:53 UTC, LizaGrebenshchikova commented on csharpTasks/task1/MyVector/MyVector/Vector.cs
> +                throw new DivideByZeroException();
Неинформативный комментарий

2018-10-25 21:34 UTC, Sdernal requested changes
Остались мелкие недочеты и все-таки я бы при операциях с нулевым вектором не кидал исключение, а возвращал  фиксированное значение. Но раз кидаешь исключения, то ок.

2018-10-25 21:34 UTC, Sdernal commented on csharpTasks/task1/MyVector/MyVector/Vector.cs
> +            return $"({this.X.ToString()}, {this.Y.ToString()})";
inline-строки сами преобразуют в строку, не нужно ToString Писать

2018-10-25 21:34 UTC, Sdernal commented on csharpTasks/task1/MyVector/MyVector/Vector.cs
> +                throw new Exception("Can't divide Vector by zero");
Я же писал, что DivideByZeroException() нормас, т.е. хорошо

2018-10-25 21:34 UTC, Sdernal commented on csharpTasks/task1/MyVector/MyVector/VectorExtensions.cs
> +        public static void SetPrecision(double EPS)
Вот это конечно не тру, задавать параметры статического класса - это некрасиво. Лучше передавать в качестве параметров  в методы со значением по-умолчанию

2018-10-25 21:34 UTC, Sdernal commented on csharpTasks/task1/MyVector/MyVector/VectorExtensions.cs
> +            if (v.Length() < EPS_)
А тут не наоборот?

2018-10-25 21:34 UTC, Sdernal commented on csharpTasks/task1/MyVector/MyVector/Program.cs
> +                (new Vector()).GetOrthogonal();
Все-таки конструктор по-умолчанию я бы задал явно и добавить комментарий, чтобы было понятно, что мы считаем "неинициализированным" вектором. Конечно поля сами нулями заполнятся, но все же.

2018-12-09 15:52 UTC, LizaGrebenshchikova commented on csharpTasks/task1/MyVector/MyVector/Program.cs
> +                (new Vector()).GetOrthogonal();
Но это же структура, нельзя задавать конструктор по умолчанию.

2018-12-09 15:55 UTC, LizaGrebenshchikova commented on csharpTasks/task1/MyVector/MyVector/Vector.cs
> +            String result = '(' + this.X_.ToString() + ", " + this.Y_.ToString() + ')';
Поправила.

2018-12-09 15:55 UTC, LizaGrebenshchikova commented on csharpTasks/task1/MyVector/MyVector/Vector.cs
> +            return $"({this.X.ToString()}, {this.Y.ToString()})";
Поправила.

2018-12-09 15:56 UTC, LizaGrebenshchikova commented on csharpTasks/task1/MyVector/MyVector/Vector.cs
> +                throw new Exception("Can't divide Vector by zero");
Поправила.

2018-12-09 15:56 UTC, LizaGrebenshchikova commented on csharpTasks/task1/MyVector/MyVector/VectorExtensions.cs
> +        public static void SetPrecision(double EPS)
Поправила.

2018-12-09 15:56 UTC, LizaGrebenshchikova commented on csharpTasks/task1/MyVector/MyVector/VectorExtensions.cs
> +            if (v.Length() < EPS_)
Поправила.

2018-12-09 16:02 UTC, Sdernal commented on csharpTasks/task1/MyVector/MyVector/Program.cs
> +                (new Vector()).GetOrthogonal();
Я наверное имел в виду некоторый статический метод: public static Vector ZeroVector() {
return new Vector {X = 0, Y = 0};
}

2018-12-09 16:02 UTC, Sdernal commented on csharpTasks/task1/MyVector/MyVector/Program.cs
> +                (new Vector()).GetOrthogonal();
А так да, ты права

2018-12-09 16:56 UTC, LizaGrebenshchikova commented on csharpTasks/task1/MyVector/MyVector/Program.cs
> +                (new Vector()).GetOrthogonal();
Поправила.

2018-12-09 16:56 UTC, Sdernal commented
Принято

2018-12-09 16:56 UTC, closed without merging