Task4
Sdernal/net-kis pull request #33
Opened 2019-05-12 19:47 UTC by NikitaSikalov

2019-05-16 19:08 UTC, Sdernal requested changes
Почти все тесты повторяют тестируемые методы - это не тесты

2019-05-16 19:08 UTC, Sdernal commented on csharpTasks/task4/LinqTask/LinqTask/ReviewContext.cs
> +           return reviews.Where(u => u.Movie == movieName).Count() != 0;
Кажется есть более логичный способ .Any

2019-05-16 19:08 UTC, Sdernal commented on csharpTasks/task4/LinqTask/LinqTask.Test/UnitTest1.cs
> +        public void BestMovies(int userId, int minimalRate)
Логика теста повторяет логику метода - тесты должны быть максимально тупыми, иначе придется писать тесты на тесты

2019-05-16 19:08 UTC, Sdernal commented on csharpTasks/task4/LinqTask/LinqTask.Test/UnitTest1.cs
> +        public void SumMarks(int userId)
аналогично предыдущему

2019-05-17 19:33 UTC, NikitaSikalov commented
Исправил тесты

2019-05-17 19:41 UTC, Sdernal commented
Принято

2019-05-17 19:41 UTC, closed without merging