Added task2
Sdernal/net-kis pull request #9
Opened 2018-10-21 13:48 UTC by pyspice

Ковариантность не завелась(

2018-10-25 21:14 UTC, Sdernal requested changes
В общем нет, такое не пойдет: нельзя хардкодить провайдеры в самой фабрике.  Это задание на интерфейсы и Дженерики. Используй их

2018-10-25 21:14 UTC, Sdernal commented on csharpTasks/task2/Factory/Factory/Data.cs
> +    abstract class Transport : IMovable {
Зачем здесь абстрактный класс?

2018-10-25 21:14 UTC, Sdernal commented on csharpTasks/task2/Factory/Factory/Data.cs
> +        protected int Wheels_;
А чем свойства не устроили?

2018-10-25 21:14 UTC, Sdernal commented on csharpTasks/task2/Factory/Factory/Factory.cs
> +        public void AddProvider(TransportProvider Provider) {
А если я хочу добавить Дирижабль-провайдер?

2018-10-25 21:56 UTC, pyspice commented on csharpTasks/task2/Factory/Factory/Data.cs
> +        protected int Wheels_;
Я не получаю инфо о состоянии машины извне, но наследовать количество колес нужно, следовательно, protected-поле - наиболее логичный выбор

2018-10-25 22:00 UTC, pyspice commented on csharpTasks/task2/Factory/Factory/Factory.cs
> +        public void AddProvider(TransportProvider Provider) {
Тогда как записывать провайдер без явного сравнения типов (или имен типов)?

2018-10-25 22:04 UTC, pyspice commented on csharpTasks/task2/Factory/Factory/Data.cs
> +    abstract class Transport : IMovable {
Чтобы было к чему преобразовывать (у IMovable нет имени, а двигаться может и планета, и в частности частица, и было бы странно, если бы в каждую частицу было зашито имя)

2018-10-25 22:05 UTC, Sdernal commented on csharpTasks/task2/Factory/Factory/Data.cs
> +        protected int Wheels_;
Ну, запрещать пользователю получить кол-во колес, ну такое...

2018-10-25 22:06 UTC, Sdernal commented on csharpTasks/task2/Factory/Factory/Factory.cs
> +        public void AddProvider(TransportProvider Provider) {
Дженерики

2018-10-25 22:06 UTC, Sdernal commented on csharpTasks/task2/Factory/Factory/Factory.cs
> +        public void AddProvider(TransportProvider Provider) {
Подсказка: список объектов интерфейса

2018-10-25 22:11 UTC, Sdernal commented on csharpTasks/task2/Factory/Factory/Data.cs
> +    abstract class Transport : IMovable {
Если хочется себе усложнить жизнь добавлением абстрактного класса, то ок

2018-10-26 07:12 UTC, pyspice commented on csharpTasks/task2/Factory/Factory/Factory.cs
> +        public void AddProvider(TransportProvider Provider) {
Ну блин, я про это как бы и спросил(

2018-10-26 07:14 UTC, pyspice commented on csharpTasks/task2/Factory/Factory/Factory.cs
> +        public void AddProvider(TransportProvider Provider) {
Хорошо, по-другому
У нас есть набор провайдеров, нормально будет производить сравнение типов по именам типов? Скажем, есть лист/мапа с провайдерами, и ключ сравнения - typeof(T).Name

2018-10-26 07:52 UTC, Sdernal commented on csharpTasks/task2/Factory/Factory/Factory.cs
> +        public void AddProvider(TransportProvider Provider) {
Вообще имена типов - это уже рефлексия и мы её еще не проходили. Можно в принципе и так,  а можно просто пытаться скастить все провайдеры к нужному.

2018-10-26 17:46 UTC, pyspice commented on csharpTasks/task2/Factory/Factory/Factory.cs
> +        public void AddProvider(TransportProvider Provider) {
Cкастить все провайдеры к нужному - это как?

2018-10-26 17:59 UTC, Sdernal commented on csharpTasks/task2/Factory/Factory/Factory.cs
> +        public void AddProvider(TransportProvider Provider) {
Все - что у тебя в списке лежит, нужный T, берешь и приводишь типы, если не null, значит возвращаешь элемент списка

2018-10-26 18:03 UTC, pyspice commented on csharpTasks/task2/Factory/Factory/Factory.cs
> +        public void AddProvider(TransportProvider Provider) {
А, ок, то есть провайдеры нельзя наследовать друг от друга. Либо строить дерево наследований, и при добавлении провайдера его обновлять... Страшно, если есть цепочка классов с кучей свойств, в каждом провайдере нужно прописывать каждое свойство(

2018-10-26 18:13 UTC, pyspice commented on csharpTasks/task2/Factory/Factory/Factory.cs
> +        public void AddProvider(TransportProvider Provider) {
Можно псевдокод метода AddProvider? Тогда либо я сразу все пойму, либо уже никогда не пойму)

2018-10-26 18:15 UTC, Sdernal commented on csharpTasks/task2/Factory/Factory/Factory.cs
> +        public void AddProvider(TransportProvider Provider) {
List<IFactoryProvider<IMovable>> providers;
public void AddProvider<T>(T provider) where T : IFactoryProvider<IMovable> { 
            providers.Add(provider);
        }

2018-10-26 18:18 UTC, pyspice commented on csharpTasks/task2/Factory/Factory/Factory.cs
> +        public void AddProvider(TransportProvider Provider) {
Ладно, ок, видимо, я понял раньше. Но с цепочкой наследований классов с кучей свойств тогда придется копипастить жестко

2018-12-08 13:27 UTC, Sdernal reviewed
В целом, архитектуру выправил, ответь на комменты и зачтем

2018-12-09 12:32 UTC, pyspice commented on csharpTasks/task2/Factory/Factory/Data.cs
> +    abstract class Transport : IMovable {
Ок

2018-12-09 12:39 UTC, Sdernal commented
Ладно, не будем упарываться в полях(свойствах) у транспорта, в общем я бы сделал их свойствами, чтобы у того, кто получает объект были ручки для получения информации. В общем, принято.

2018-12-09 12:40 UTC, pyspice commented on csharpTasks/task2/Factory/Factory/Data.cs
> +        protected int Wheels_;
Поправил

2018-12-09 12:44 UTC, Sdernal commented
Public readonly-поле, ну ок, можно и так. Вообще очень многие подобные вещи в C# любят делать с помощью свойств. Это хорошо видно в моделях для MVC. Все, закрываю, пулл реквест. Принято (еще раз)

2018-12-09 12:44 UTC, closed without merging